spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/loans_ms_db
    password: root123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



server:
  port: 8090